name: Deploy Python App

on:
  push:
    branches:
      - main  # Deploy when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Use the appropriate Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}  # Heroku API key from GitHub Secrets
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku auth:token
          heroku git:remote -a your-heroku-app-name
          git push heroku main

